name: py_base
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - pip
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - ipython
  - tqdm
  - ipywidgets
  - anndata
  - scanpy
  - umap-learn
  - python-lsp-black
  - flake8
  - pyright
