name: torch
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.13
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pip
  - datasets
  - transformers
  - ray
  - flash-attn
  - pyarrow
  - accelerate
  - cellxgene_census
  - tiledbsoma
  - pandas
  - numpy
  - scikit-learn
  - ipython
  - tqdm
  - ipywidgets
  - anndata
  - loompy
  - scanpy
  - umap-learn
  - matplotlib
  - seaborn
  - python-lsp-black
  - flake8
  - pyright
